<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class ChoicesTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    function 그룹원만_투표를_할_수_있다()
    {

    }

    function 그룹원만_투표를_수정할_수_있다()
    {

    }

    function 다중_투표는_할_수_없다()
    {

    }
}
